### ISSUE TITLE
[BUG] Running Time

### ISSUE THREAD

**Issue by nbei** [Atlas200dk/sample-imageinpainting-HiFill#1]
Thanks for sharing code of your novel and inspiring work. However, when I runing your code, I got the following error:
```bash
F tensorflow/core/framework/tensor_shape.cc:44] Check failed: NDIMS == dims() (2 vs. 4)Asking for tensor of 2 dimensions from a tensor of 4 dimensions 
```
I'm using tensorflow 1.6 with TitanXp.

**Comment by duxingren14** [comment]
Thanks for the feedback. I am using gtx 1080 ti.  It works well.  I also got some feedback that tensorflow-gpu <= 1.10 does not work on some machine. Can you please try later versions such as tensorflow-gpu=1.13
