### ISSUE TITLE
Is there anyway to run in 1.7x version Ascend ADK?

### ISSUE THREAD

**Issue by arthurcarneiro** [Atlas200dk/sample-imageinpainting-HiFill#18]
Hello, 

I've been trying to use this project, but I use the 20.1 CANN with 1.7x. It changed from the 1.3x version and we haven't a hiai library anymore, everything is made using ACL. I can't see a hiai--acl documentation with more information about this transition. I'd like to know if there's anything being made to upgrade this application.

Thanks and Congratulations for the job.

**Comment by ascendhuawei** [comment]
please check this repo
https://github.com/Ascend/samples/tree/master/python/level2_simple_inference/6_other/imageinpainting_hifill
