### ISSUE TITLE
some bad example？

### ISSUE THREAD

**Issue by ljjcoder** [Atlas200dk/sample-imageinpainting-HiFill#3]
![Places365_val_00000327_masked](https://user-images.githubusercontent.com/40750189/83258870-a3749580-a1e9-11ea-9359-fecfa42e7030.png)
![22 png_inpainted](https://user-images.githubusercontent.com/40750189/83258890-aa030d00-a1e9-11ea-8cda-1351b48e2d5a.jpg)
thansks for your excellent work！when I test the example images you provide with your code, It perform very well.  However, if we test the image shown above (400x600), it perform very bad. The result of completion will be a little blurry. I noticed that the minimum rate of change you tested in the experiment was 512x512. Does that mean that the algorithm needs to be on large images to get good results?

**Comment by duxingren14** [comment]
Thanks for the feedback. Based on our observation, our model peforms almost equally on small images and large images. We have to admit that given an input  image and a casually-drawn mask, there are some possibilities that our method gonna fail, just as the failure examples shown in the supplementary materials. We appreciate the failure example you shared. We are working hard to improve the method further. Hopefully we will have some positive outputs  in the near future.

**Comment by ljjcoder** [comment]
@duxingren14 thanks for your reply.  I further tested your algorithm on 256x256 resolution images, using some extremely thick masks, like this
input:

![0input_Places365_val_00000968](https://user-images.githubusercontent.com/40750189/83329159-72b06100-a2ba-11ea-8b3e-ddcad9548789.png)
yours:


![Places365_val_00000968](https://user-images.githubusercontent.com/40750189/83329193-ad19fe00-a2ba-11ea-9555-5cbf2fed41ec.png)
edgeconnect:
![Places365_val_00000968](https://user-images.githubusercontent.com/40750189/83329206-c1f69180-a2ba-11ea-8e23-d9e85a225d61.png)
We found that in this case, edgeconnect performed better. After testing 1,000 test images, the EC psnr was 22.428, and your psnr was 18.702.  Whether your algorithm needs to scale the tested image to 256 size, the mask area cannot be too dense. If so, then replace the inpainting module in your algorithm with edgeconnect, and then use the super-resolution method you designed. Will you get better results.

**Comment by duxingren14** [comment]
@ljjcoder, really appreciate the evaluation. We will do more evaluations on EdgeConnect and definitely try what you recommended.

**Comment by duxingren14** [comment]
Recently I did some more tests on both models. Here are some discoveries: 1. edgeconnect generally did better in inpainting edge structures, 2. EdgeConnect did better when mask percentage is over 30%,, while  HiFill is prone to suffer "gray-strip" artifacts; 3, EdgeConnect did wrose in maintaining color consistency. It genuinely a good idea to merge the two to get a better model than either of the two.

**Comment by duxingren14** [comment]
The color consistency issue of EdgeConnect is shown as below, which is very typical for EdgeConnect.
  input          ____________________________     ______________    hifill    _______________     _____________________          edgeconnect
![0011](https://user-images.githubusercontent.com/2570875/84721649-ff535400-af35-11ea-89f1-bc7404f19aa1.png)
![0057](https://user-images.githubusercontent.com/2570875/84721653-02e6db00-af36-11ea-8194-85e08e592e3e.png)
![0251](https://user-images.githubusercontent.com/2570875/84721660-05493500-af36-11ea-9365-a6aee30b8c61.png)

**Comment by kelisiya** [comment]
> The color consistency issue of EdgeConnect is shown as below, which is very typical for EdgeConnect.
> input ____________________________ ______________ hifill _______________ _____________________ edgeconnect
> ![0011](https://user-images.githubusercontent.com/2570875/84721649-ff535400-af35-11ea-89f1-bc7404f19aa1.png)
> ![0057](https://user-images.githubusercontent.com/2570875/84721653-02e6db00-af36-11ea-8194-85e08e592e3e.png)
> ![0251](https://user-images.githubusercontent.com/2570875/84721660-05493500-af36-11ea-9365-a6aee30b8c61.png)

I am very interested in your work on EdgeConnect+HiFill_SR. Would you like to open source or share this merged work with me?
