### ISSUE TITLE
Attention Computing Branch architecture

### ISSUE THREAD

**Issue by clementabary** [Atlas200dk/sample-imageinpainting-HiFill#5]
Hi, thanks a lot for your research and your detailed explanations !

I still have question about the architecture of the attention computing branch. What does [P] stands for after the downsampling step ? It is described as a high-level feature map (compared to [P^l=3]) with several additional layers in Fig. 2, but not mentioned in the Appendix.

**Comment by duxingren14** [comment]
Thanks for your quesiton.  P is the feature map (or activation values of certain layers). I recommend you to look into the pb file for detailed architecture, as the figure 2 is only fo visualization purpos, which is not adequate enough.

**Comment by duxingren14** [comment]
You may use the viewing tool Netron to look into pb file.

**Comment by clementabary** [comment]
Thanks ! Looking forward to your implementation of attention computing/transfer modules
