### ISSUE TITLE
Source of high resolution test samples

### ISSUE THREAD

**Issue by jingyuanli001** [Atlas200dk/sample-imageinpainting-HiFill#8]
Hi, thanks for your excellent work.

I've read your paper and I'm really impressed by the results in your paper. But I am having some question when trying to test the model. I would appreciate it if you could provide some help.
In the experiment part, it's mentioned that the model is tested in several different resolutions, from 512*512 to 8K. However, when I was testing the model, I found that the images in Places2 dataset are at most 512 pixels, and there seems to have no ground truth image whose size is really larger than 512. If the high resolution samples are produced by resizing the 512*512 images, it seems that the evaluations on high resolution images are actually equivalent to that on 512*512 because each part of the model is essentially working on the 512 bases (including the ground truth). Am I misunderstanding something or there is another source of private testing samples?

Thanks for any help in advance :).

**Comment by duxingren14** [comment]
For our model HiFill, the test results do not vary much by the size of raw input images. However, for other methods, it matters a lot.

Please find more detils here:
https://github.com/duxingren14/Hifill-tensorflow
