### ISSUE TITLE
Convolution for mask and attention score training

### ISSUE THREAD

**Issue by liwenxi** [Atlas200dk/sample-imageinpainting-HiFill#9]
I noticed that a 7x7 kernel is used in the model to process the mask. Why do you want to do this operation? And how to train this module? In addition, attention score didn't work very well in my own training, because the score of each patch was always average. Are there any suggestions you can give me?

**Comment by duxingren14** [comment]
Hi, please find more details here

https://github.com/duxingren14/Hifill-tensorflow
